# Generated by Django 3.1.3 on 2020-11-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movieid', models.IntegerField(blank=True, db_column='movieId', primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, null=True)),
                ('genre', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('userid', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('movieid', models.IntegerField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ratings',
                'managed': False,
            },
        ),
    ]
